# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.welcomeLabel = QtWidgets.QLabel(self.centralwidget)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.verticalLayout.addWidget(self.welcomeLabel)
        self.genreComboBox1 = QtWidgets.QComboBox(self.centralwidget)
        self.genreComboBox1.setObjectName("genreComboBox1")
        self.verticalLayout.addWidget(self.genreComboBox1)
        self.genreComboBox2 = QtWidgets.QComboBox(self.centralwidget)
        self.genreComboBox2.setObjectName("genreComboBox2")
        self.verticalLayout.addWidget(self.genreComboBox2)
        self.formatLayout = QtWidgets.QHBoxLayout()
        self.formatLayout.setObjectName("formatLayout")
        self.printRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.printRadioButton.setObjectName("printRadioButton")
        self.formatLayout.addWidget(self.printRadioButton)
        self.digitalRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.digitalRadioButton.setObjectName("digitalRadioButton")
        self.formatLayout.addWidget(self.digitalRadioButton)
        self.verticalLayout.addLayout(self.formatLayout)
        self.fictionCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.fictionCheckBox.setObjectName("fictionCheckBox")
        self.verticalLayout.addWidget(self.fictionCheckBox)
        self.selectionList = QtWidgets.QListWidget(self.centralwidget)
        self.selectionList.setObjectName("selectionList")
        self.verticalLayout.addWidget(self.selectionList)
        self.recommendButton = QtWidgets.QPushButton(self.centralwidget)
        self.recommendButton.setObjectName("recommendButton")
        self.verticalLayout.addWidget(self.recommendButton)
        self.recommendationWidget = QtWidgets.QWidget(self.centralwidget)
        self.recommendationWidget.setObjectName("recommendationWidget")
        self.recommendationLayout = QtWidgets.QVBoxLayout(self.recommendationWidget)
        self.recommendationLayout.setObjectName("recommendationLayout")
        self.verticalLayout.addWidget(self.recommendationWidget)
        self.dateLayout = QtWidgets.QHBoxLayout()
        self.dateLayout.setObjectName("dateLayout")
        self.dateLabel = QtWidgets.QLabel(self.centralwidget)
        self.dateLabel.setObjectName("dateLabel")
        self.dateLayout.addWidget(self.dateLabel)
        self.readingDateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.readingDateEdit.setObjectName("readingDateEdit")
        self.dateLayout.addWidget(self.readingDateEdit)
        self.verticalLayout.addLayout(self.dateLayout)
        self.commentEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.commentEdit.setObjectName("commentEdit")
        self.verticalLayout.addWidget(self.commentEdit)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.addToListButton = QtWidgets.QPushButton(self.centralwidget)
        self.addToListButton.setObjectName("addToListButton")
        self.buttonLayout.addWidget(self.addToListButton)
        self.viewListButton = QtWidgets.QPushButton(self.centralwidget)
        self.viewListButton.setObjectName("viewListButton")
        self.buttonLayout.addWidget(self.viewListButton)
        self.restartButton = QtWidgets.QPushButton(self.centralwidget)
        self.restartButton.setObjectName("restartButton")
        self.buttonLayout.addWidget(self.restartButton)
        self.verticalLayout.addLayout(self.buttonLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BookTok აპი"))
        self.welcomeLabel.setText(_translate("MainWindow", "კეთილი იყოს თქვენი მობრძანება BookTok-ში"))
        self.printRadioButton.setText(_translate("MainWindow", "ბეჭდური"))
        self.digitalRadioButton.setText(_translate("MainWindow", "ციფრული"))
        self.fictionCheckBox.setText(_translate("MainWindow", "მხატვრული ლიტერატურა"))
        self.recommendButton.setText(_translate("MainWindow", "მიიღე რჩევა"))
        self.dateLabel.setText(_translate("MainWindow", "აირჩიე წასაკითხი თარიღი:"))
        self.commentEdit.setPlaceholderText(_translate("MainWindow", "დაწერე კომენტარი..."))
        self.addToListButton.setText(_translate("MainWindow", "წასაკითხ სიაში დამატება"))
        self.viewListButton.setText(_translate("MainWindow", "სიის ნახვა"))
        self.restartButton.setText(_translate("MainWindow", "განახლება"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
